// <auto-generated />
using System;
using FutsalReservation.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutsalReservation.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615073626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutsalReservation.Api.Models.Lapangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HargaPerJam")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lapangan");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Pembayaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Metode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReservasiId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("TanggalBayar")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReservasiId")
                        .IsUnique();

                    b.ToTable("Pembayaran");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Reservasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catatan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<int>("JamMulai")
                        .HasColumnType("int");

                    b.Property<int>("JamSelesai")
                        .HasColumnType("int");

                    b.Property<int>("LapanganId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LapanganId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservasi");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Pembayaran", b =>
                {
                    b.HasOne("FutsalReservation.Api.Models.Reservasi", "Reservasi")
                        .WithOne("Pembayaran")
                        .HasForeignKey("FutsalReservation.Api.Models.Pembayaran", "ReservasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservasi");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Reservasi", b =>
                {
                    b.HasOne("FutsalReservation.Api.Models.Lapangan", "Lapangan")
                        .WithMany("DaftarReservasi")
                        .HasForeignKey("LapanganId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutsalReservation.Api.Models.User", "User")
                        .WithMany("DaftarReservasi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lapangan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Lapangan", b =>
                {
                    b.Navigation("DaftarReservasi");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.Reservasi", b =>
                {
                    b.Navigation("Pembayaran");
                });

            modelBuilder.Entity("FutsalReservation.Api.Models.User", b =>
                {
                    b.Navigation("DaftarReservasi");
                });
#pragma warning restore 612, 618
        }
    }
}
